/**
 * ============================================================================
 * DATA TYPES
 * ----------------------------------------------------------------------------
 * This file holds two families of shapes, and it matters which one you use.
 *
 *   1. `Product` / `Category`  — THE DATABASE ROWS.
 *      One property per column in Supabase, named exactly as the column is
 *      named (snake_case, `title_ka`, `created_at`, ...). Anything that talks
 *      to Supabase uses these. This is where the site is heading.
 *
 *   2. `SeedProduct` / `SeedCategory` — THE LOCAL CATALOGUE FILES.
 *      The richer hand-written shapes used by products.ts and categories.ts
 *      while the catalogue still lives in the repository. They stay until the
 *      content has been moved into Supabase, then they go.
 *
 * Both exist at once on purpose: pages migrate one at a time, so for a while
 * some read the database and some read the files.
 * ============================================================================
 */

/* -------------------------------------------------------------------------- */
/* 1. Database rows                                                           */
/* -------------------------------------------------------------------------- */

/**
 * A row of the `categories` table.
 *
 * Translated columns are stored side by side rather than in a nested object,
 * because a database column cannot hold a shape — `title_ka` and `title_en`
 * are two real columns.
 */
export interface Category {
  /** Primary key. A uuid generated by the database. */
  id: string
  /** Appears in the URL: /ka/catalog/living-room. Unique across the table. */
  slug: string
  title_ka: string
  title_en: string
  /** Timestamp written by the database, ISO 8601. */
  created_at: string

  /*
   * The three below are OPTIONAL, and that is not laziness.
   *
   * They were added by supabase-schema.sql after the first version of the
   * table shipped. A database that has not had that file run against it still
   * answers queries — it just answers them without these columns — so the
   * types say `?` and every reader goes through the helpers in
   * src/lib/localize.ts, which supply a sane default.
   *
   * Once the migration has run everywhere, drop the `?` and the fallback
   * branch in src/lib/queries.ts together.
   */

  /**
   * Which half of the catalogue this belongs to: home furniture or office.
   *
   * VESTIGIAL. This was the two-way split before the catalogue became a tree;
   * the top-level rows are the grouping now. supabase-category-tree.sql drops
   * the check constraint but keeps the column, so nothing that still reads it
   * breaks. Nothing in this codebase does any more.
   */
  group_key?: CategoryGroup | null
  /** Banner photograph for the category card. */
  image?: string | null
  /** Ascending display order WITHIN THE PARENT. Ties fall back to slug. */
  sort_order?: number | null

  /*
   * The three below arrive with supabase-category-tree.sql, and are optional
   * for the same reason as the three above: a database that has not had that
   * file run against it still answers queries, just without these columns.
   * Readers go through src/lib/category-tree.ts, which supplies the defaults
   * that make an un-migrated database behave exactly like a flat catalogue.
   */

  /** Parent category, or null/undefined for a top-level row. */
  parent_id?: string | null
  /**
   * The office's on/off switch. An inactive category and everything under it
   * is hidden from public navigation but keeps its products and its URL.
   */
  is_active?: boolean | null
  /** Pinned and given a photograph in the mega menu. Independent of order. */
  featured?: boolean | null
}

/** The top-level split the home page offers: home furniture vs office. */
export type CategoryGroup = 'home' | 'office'

/*
 * NOTE: the live `categories` table has NO description columns — verified
 * against the database, which returns exactly:
 *   id, slug, title_ka, title_en, created_at (+ the three optional columns)
 * So category pages have no intro paragraph to show. If you want one, add
 * `description_ka` and `description_en` to the table and then add them here;
 * nothing else needs to change.
 */

/**
 * A row of the `products` table.
 *
 * `category_id` is a foreign key pointing at `Category.id` — note that it is
 * the id, not the slug, so renaming a category's slug no longer orphans its
 * products the way it does in the local files.
 */
export interface Product {
  /** Primary key. A uuid generated by the database. */
  id: string
  /** Appears in the URL: /ka/product/aria-oak-dining-table. Unique. */
  slug: string
  title_ka: string
  title_en: string
  description_ka: string
  description_en: string
  /** Foreign key -> categories.id */
  category_id: string
  /**
   * Free text, not numbers — e.g. "W 220 x D 95 x H 75 cm". Stored as written
   * so a piece that is round, extendable or irregular can still be described.
   */
  dimensions: string
  materials_ka: string
  materials_en: string
  /** COVER PHOTO FIRST. Stored as a text[] column. */
  images: string[]
  /** Eligible for featured placement on the home page. */
  featured: boolean
  /** Timestamp written by the database, ISO 8601. Used for "newest" sorting. */
  created_at: string

  /**
   * Soft delete. True hides the piece from the public site while keeping it in
   * the admin dashboard, where an administrator can restore it or delete it
   * for real.
   *
   * OPTIONAL for the same reason as `price`: the column is added by
   * supabase-rbac.sql, so a database that has not had that file run against it
   * has no such column. Read it as `product.is_archived === true` rather than
   * as a plain boolean, so an undefined means "live", which is what a database
   * without archiving has.
   */
  is_archived?: boolean | null

  /**
   * When the piece was archived, as an ISO timestamp. Null — or absent — means
   * it is live.
   *
   * The database sets this itself, in step with `is_archived`, and thirty days
   * later the piece is deleted for real. See supabase-retention.sql. Nothing
   * in the app writes it; the dashboard only reads it, to say how long an
   * archived piece has left.
   */
  deleted_at?: string | null

  /**
   * Internal reference price, entered in the admin dashboard.
   *
   * OPTIONAL, and it stays optional: the column is added by
   * supabase-admin-setup.sql, so a database that has not had that file run
   * against it has no such column — the same reasoning as the three optional
   * columns on Category above.
   *
   * NOT SHOWN ANYWHERE ON THE PUBLIC SITE. Every product reads "Price on
   * request" by design, because no two commissions are quoted the same. This
   * is here so the office can keep a number against a piece for itself.
   */
  price?: number | null

  /**
   * Foreign key -> brands.id. The house that makes the piece.
   *
   * OPTIONAL, and nullable in the database too. Most of the catalogue predates
   * the brands table and a piece whose manufacturer is not recorded is a
   * normal state rather than an error — so this is read as "unknown" when
   * absent, never as a failure. Added by supabase-brands.sql, which is also
   * why the type allows the column to be missing entirely.
   */
  brand_id?: string | null
}

/**
 * One partner manufacturer.
 *
 * WHY THIS IS A TABLE AND NOT A CONSTANT
 *   These twenty-nine were a hardcoded array in src/data/company.ts, which is
 *   why `website` and `description_*` were empty on every one of them: both
 *   are facts only the office holds, and neither could be filled in without a
 *   developer editing TypeScript. They are nullable here for the same reason
 *   they were empty there — they are genuinely not known yet — and the brands
 *   page renders each the moment it is set.
 */
export interface Brand {
  id: string
  /** Appears in no URL today, but is the stable key the seed matches on. */
  slug: string
  name: string
  /**
   * One of the six the interface can label. Constrained in the database,
   * because the chip row and the card badge both read their text from the
   * locale key `b2b.brands.<discipline>` — an unlabelled seventh value would
   * render as a missing key rather than as a name.
   */
  discipline: string
  /** Where the house is from. Shown small, under the name. */
  country: string | null
  /** A room this house's work belongs in. Not their own photography. */
  image: string | null
  /** A licensed logo file, when the office has one. */
  logo: string | null
  website: string | null
  description_ka: string | null
  description_en: string | null
  sort_order: number
  is_active: boolean
  created_at: string
}

/* -------------------------------------------------------------------------- */
/* 2. Local catalogue files                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Text that exists in both languages.
 * Every visitor-facing string in the local catalogue uses this shape:
 *
 *   name: { ka: "მაგიდა", en: "Table" }
 *
 * Both are required — if one is missing TypeScript flags it, which stops
 * a half-translated product reaching the site.
 */
export type Localized = {
  ka: string
  en: string
}

/** A sub-group inside a category, e.g. "Sofas" inside "Living room". */
export type Subcategory = {
  /** URL fragment. Lowercase, hyphens only, must be unique in its category. */
  slug: string
  name: Localized
}

export type SeedCategory = {
  id: string
  /** Appears in the URL: /ka/catalog/living-room */
  slug: string
  name: Localized
  /** Banner + category-card photograph. */
  image: string
  /** Short paragraph shown on the category page under the banner. */
  intro: Localized
  subcategories: Subcategory[]
}

/** Whether a piece can be delivered now, ordered in, or made to measure. */
export type Availability = 'in-stock' | 'on-order' | 'custom'

/** A colour/finish option, shown as a small swatch on the product page. */
export type Finish = {
  name: Localized
  /** Hex value used to paint the swatch, e.g. "#6B4E32". */
  hex: string
}

export type SeedProduct = {
  id: string
  /** Appears in the URL: /ka/product/aria-oak-dining-table */
  slug: string
  /** Printed on the product card and used by catalogue search. */
  articleNumber: string
  categorySlug: string
  subcategorySlug: string
  /** Empty string when the piece belongs to no collection. */
  collectionSlug: string
  name: Localized
  /** One line, shown on cards. */
  shortDescription: Localized
  /** Two or three sentences, shown on the product page. */
  description: Localized
  /** COVER PHOTO FIRST. A second photo enables the hover swap on cards. */
  images: string[]
  /** Human-readable material summary, e.g. "Solid oak, natural oil". */
  materials: Localized
  /** Centimetres. */
  dimensions: { width: number; depth: number; height: number }
  finishes: Finish[]
  availability: Availability
  /** Country of origin, shown in the specification table. */
  origin: Localized
  /** Warranty length in months. */
  warrantyMonths: number
  /** Adds the "New" badge and puts the piece in the home-page row. */
  isNew: boolean
  /** Eligible for featured placement on the home page. */
  isFeatured: boolean
}

export type Collection = {
  id: string
  slug: string
  name: Localized
  /** One-line summary for the collections index. */
  tagline: Localized
  /** The longer story paragraph on the collection page. */
  story: Localized
  /** Large cover image for the index page. */
  coverImage: string
  /** Gallery shown on the collection detail page. */
  images: string[]
}

/* -------------------------------------------------------------------------- */
/* 3. Staff                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * What somebody signed into the dashboard is allowed to do.
 *
 *   admin     everything: delete, restore an archived piece, manage staff
 *   operator  create, edit and archive; no deleting and no staff management
 *
 * The authority is the `role` column on the `admins` table, checked by row
 * level security on every statement — NOT this type, and not anything the
 * browser believes. What the browser knows only decides which buttons appear.
 */
export type StaffRole = 'admin' | 'operator'

/** A row of the `admins` table. Read it as "staff"; the name is historical. */
export interface StaffMember {
  /** Primary key, and a foreign key to auth.users.id. */
  user_id: string
  /** Copied from the auth account so the list is readable at a glance. */
  email: string | null
  role: StaffRole
  created_at: string
}
